---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-gke-01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/pv-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-gke-01
  namespace: default
  labels:
    app: odoo-gke
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-gke-02
  namespace: default
  labels:
    app: odoo-gke
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-gke-03
  namespace: default
  labels:
    app: odoo-gke
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi